spring:
  application:
    name: pospre
        #数据源配置
  datasource:
        name: sgx
        url: jdbc:sqlserver://192.168.2.111:1433;database=pos1;integratedSecurity=false
        username: sa
        password: coing
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        initialize: true
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        tomcat:
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
          #mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:logback.xml